[project]
name = "thesis-robust-e2e-vision-ads"
version = "0.1.0"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["eval", "scripts", "external", "metrics"]
